<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_ _switcher-indicator</name>
   <tag></tag>
   <elementGuidId>d51aa4de-bd2c-4e9f-a444-d83fdaa6ee66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/app-merchant-configuration/div/app-merchant-details/form/app-layout-fixed/div/div/div/app-secured-form/app-secured-content/fieldset/div/lib-rc-switcher/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>switcher-indicator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>activeBusiness</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-merchant-configuration[1]/div[@class=&quot;merchant-configuration-wrapper&quot;]/app-merchant-details[1]/form[@class=&quot;merchant-details ng-untouched ng-pristine ng-valid&quot;]/app-layout-fixed[1]/div[@class=&quot;d-flex fixed-container-wrapper&quot;]/div[@class=&quot;fixed-container&quot;]/div[@class=&quot;merchant-details-wrapper&quot;]/app-secured-form[1]/app-secured-content[1]/fieldset[1]/div[@class=&quot;top-part&quot;]/lib-rc-switcher[1]/div[@class=&quot;rc-switcher-wrapper&quot;]/div[@class=&quot;rc-switcher-control-wrapper&quot;]/div[@class=&quot;rc-switcher-control&quot;]/label[@class=&quot;switcher-indicator&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/app-merchant-configuration/div/app-merchant-details/form/app-layout-fixed/div/div/div/app-secured-form/app-secured-content/fieldset/div/lib-rc-switcher/div/div/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
   </webElementXpaths>
</WebElementEntity>
