<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ _custom-control-indicator</name>
   <tag></tag>
   <elementGuidId>8172ec06-9b6a-4e0f-91c7-fa14720ed012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/app-merchant-configuration/div/app-merchant-details/form/app-layout-fixed/div/div/div/app-secured-form/app-secured-content/fieldset/div[6]/div[2]/lib-rc-checkbox[2]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-control-indicator</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/app-merchant-configuration[1]/div[@class=&quot;merchant-configuration-wrapper&quot;]/app-merchant-details[1]/form[@class=&quot;merchant-details ng-untouched ng-pristine ng-valid&quot;]/app-layout-fixed[1]/div[@class=&quot;d-flex fixed-container-wrapper&quot;]/div[@class=&quot;fixed-container&quot;]/div[@class=&quot;merchant-details-wrapper&quot;]/app-secured-form[1]/app-secured-content[1]/fieldset[1]/div[@class=&quot;merchant-details-general-wrapper&quot;]/div[@class=&quot;merchant-details-checkboxes&quot;]/lib-rc-checkbox[2]/div[@class=&quot;rc-form-checkbox&quot;]/label[@class=&quot;custom-control custom-checkbox&quot;]/span[@class=&quot;custom-control-indicator&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/app-merchant-configuration/div/app-merchant-details/form/app-layout-fixed/div/div/div/app-secured-form/app-secured-content/fieldset/div[6]/div[2]/lib-rc-checkbox[2]/div/label/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lib-rc-checkbox[2]/div/label/span</value>
   </webElementXpaths>
</WebElementEntity>
